### ISSUE TITLE
Challenge input (user address) is used as user ID in ERC20Verifier contract

### ISSUE THREAD

**Issue by nedgar** [0xPolygonID/contracts#5]
In the example [ERC20Verifier](https://github.com/0xPolygonID/contracts/blob/main/contracts/examples/ERC20Verifier.sol) contract, [in `_beforeProofSubmit`](https://github.com/0xPolygonID/contracts/blob/main/contracts/examples/ERC20Verifier.sol#L28), it converts `inputs[validator.getChallengeInputIndex()]` to an address, and checks that it matches the sender.
But [in `_afterProofSubmit`](https://github.com/0xPolygonID/contracts/blob/main/contracts/examples/ERC20Verifier.sol#L49), it treats that as the user ID (`uint256 id = inputs[validator.getChallengeInputIndex()]) then and uses that to set up the bi-di mapping (`addressToId[_msgSender()] = id` and `idToAddress[id] = _msgSender()`).

So both mappings end up effectively being sets with the user address as key. This would allow multiple IDs to use the same address.

@vmidyllic says:
> thanks, it doesn’t affect a flow because challenge was ‘considered as unique identifier’ , but it’s important to have right example!

**Comment by nedgar** [comment]
@vmidyllic does the mapping need to be bidirectional? Having just the `addressToId` mapping would allow a given ID to operate multiple accounts, though a separate proof would be required for each.

**Comment by vmidyllic** [comment]
Yes, we will change the example to that, 
so each address can receive tokens once and each id can be linked only to one address.
```       // get user id from inputs
        uint256 id = inputs[1]; // user id
        // additional check didn't get airdrop tokens before
        if (idToAddress[id] == address(0) && addressToId[_msgSender()] == 0 ) {
            super._mint(_msgSender(), TOKEN_AMOUNT_FOR_AIRDROP_PER_ID);
            addressToId[_msgSender()] = id;
            idToAddress[id] = _msgSender();
        }
```
