### ISSUE TITLE
where is the implementation of  Poseidon.sol

### ISSUE THREAD

**Issue by Albertliucheng** [0xPolygonID/contracts#8]
Hi，

In the library, I can not find the implementation of the function poseidon, how can I do it? Thanks!

library PoseidonUnit5L {
    function poseidon(uint256[5] calldata) public pure returns (uint256) {}
}

library PoseidonUnit6L {
    function poseidon(uint256[6] calldata) public pure returns (uint256) {}
}

**Comment by Albertliucheng** [comment]
I have found the solution with circomlibjs generate abi in the repository

**Comment by ilya-korotya** [comment]
@Albertliucheng, could you please close your issue if the issue is resolved?
